version: "3"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    command: yarn start
    volumes:
      - .:/usr/app
  database:
    build: ./containers/database
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=sequelize_tests
